P14130_equal_to_the_last_one: P14130_equal_to_the_last_one.o
	g++ -o P14130_equal_to_the_last_one P14130_equal_to_the_last_one.o
P29094_position_of_the_maximum: P29094_position_of_the_maximum.o
	g++ -o P29094_position_of_the_maximum P29094_position_of_the_maximum.o
clear:
	rm -r *.o
